spring:
  datasource:
    url: jdbc:h2:mem:xe;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    driver-class-name: org.h2.Driver

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      database: H2
      show-sql: false
      hibernate:
        ddl-auto: create-drop
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        use-new-id-generator-mappings: true
